### PR TITLE
chore: build adapter vue inside image

### PR DESCRIPTION
**Pull request by fqutishat**
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

### CODE REVIEW

**Comment by llorllale** [comment]
@fqutishat Can you please explain the reason for this change?

I don't exactly mind this; what I **do** care about is eventually running into this issue again: trustbloc/edge-agent#173

**Comment by llorllale** [comment]
I guess what you're trying to fix is the "double build" of adapter-vue

**Comment by llorllale** [comment]
Another way this can be done is by building adapter-vue outside and copying the output in `.build/bin/adapter-vue` into the docker image.

**Comment by fqutishat** [comment]
> Another way this can be done is by building adapter-vue outside and copying the output in `.build/bin/adapter-vue` into the docker image.

all the builds should be done inside image because we can control the environment.  building adapter-vue outside is risky because we can't control the machine.

**Comment by llorllale** [comment]
> all the builds should be done inside image because we can control the environment. building adapter-vue outside is risky because we can't control the machine environment.

We're not doing this everywhere. And `make adapter-vue` was already running fine outside the docker image.

Let's try to be consistent if there are real risks. And please let's try to describe reasons for PRs, otherwise reviewers won't know what to look for.

**Comment by rolsonquadras** [comment]
> > all the builds should be done inside image because we can control the environment. building adapter-vue outside is risky because we can't control the machine environment.
> 
> We're not doing this everywhere. And `make adapter-vue` was already running fine outside the docker image.
> 
> Let's try to be consistent if there are real risks. And please let's try to describe reasons for PRs, otherwise reviewers won't know what to look for.

It's risky to build binary outside and inject into docker as npm is [platform dependent](https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list). eg, mac user will build adapter-vue with mac target and inject that bin into alpine (docker os).

**Comment by llorllale** [comment]
@rolsonquadras 

> > > all the builds should be done inside image because we can control the environment. building adapter-vue outside is risky because we can't control the machine environment.
> > 
> > 
> > We're not doing this everywhere. And `make adapter-vue` was already running fine outside the docker image.
> > Let's try to be consistent if there are real risks. And please let's try to describe reasons for PRs, otherwise reviewers won't know what to look for.
> 
> It's risky to build binary outside and inject into docker as npm is [platform dependent](https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list). eg, mac user will build adapter-vue with mac target and inject that bin into alpine (docker os).

That links to instructions on how to build Node.JS. It's not relevant to the runtime dependencies for `npm run build`.

Furthermore, the output of `make adapter-vue` is a static site that will run on the User Agent, not the docker image's internal environment.

**Pull request merged**
